

### Vamos a probar el saludo
GET  http://localhost:8080/usuario

### Vamos a probar el saludo
POST http://localhost:8080/usuario

### Vamos a probar el saludo
PUT http://localhost:8080/usuario

### Vamos a probar el saludo
DELETE http://localhost:8080/usuario












###
GET http://localhost:8080/usuario

###
POST http://localhost:8080/usuario

###
PUT http://localhost:8080/usuario

###
DELETE http://localhost:8080/usuario


###
GET http://localhost:8080/api/clasificacion

###
POST http://localhost:8080/api/clasificacion

###
PUT http://localhost:8080/api/clasificacion

###
DELETE http://localhost:8080/api/clasificacion





